### ISSUE TITLE
Docker not found?

### ISSUE THREAD

**Issue by DGxInfinitY** [timonier/extract-xiso#1]
I get this error when trying to run using the -h option:
`/usr/local/bin/extract-xiso: 3: /usr/local/bin/extract-xiso: docker: not found`
using command:
`extract-xiso -h`

**Comment by mauchede** [comment]
Hello @DGxInfinitY,

`extract-xiso` is installed in a Docker image. It is not possible to use `timonier/extract-xiso` without [Docker](https://www.docker.com/).

To install Docker, you can find information in the [Docker documentation](https://www.docker.com/community-edition). Installation depends of your OS: I can not help you more since I do not know your system.

**Comment by mauchede** [comment]
I will close this issue. Feel free to reopen it if you want to add some comments or create a new one if you have another question.

**Comment by Tea-pot** [comment]
Hi there.
I unfortunately suffering from the same issue. Error message is:
extract-xiso -h
/usr/local/bin/extract-xiso: line 14: exec: docker: not found
I have already install newest release of Docker according to:
https://docs.docker.com/install/linux/docker-ce/ubuntu/
Linux Mint 18 based on Ubuntu 16.04 – Xenial (Xerus).
Is there any hope for working solution?

**Comment by mauchede** [comment]
Hi @Tea-pot,

If you run the given command (`docker run -it ubuntu bash`), does it work?

**Comment by Tea-pot** [comment]
Hello @mauchede
Here what I have tried already:
fresh and clean installation for LinuxMint 18
https://gist.github.com/dweldon/39ca0536168a92815a56df44eb55a337
I have removed extract-xiso completely. Than re installed package from:
https://github.com/timonier/extract-xiso

<ka@ka-HP-EliteBook-2570p ~ $ sudo apt-get remove extract-xiso
[sudo] password for ka: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package extract-xiso
ka@ka-HP-EliteBook-2570p ~ $ export INSTALL_DIRECTORY=/usr/bin
ka@ka-HP-EliteBook-2570p ~ $ sudo bin/installer install
sudo: bin/installer: command not found
ka@ka-HP-EliteBook-2570p ~ $ curl --location "https://github.com/timonier/extract-xiso/raw/master/bin/installer" | sudo sh -s -- install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142  100   142    0     0      8      0  0:00:17  0:00:15  0:00:02    32
100   832  100   832    0     0     51      0  0:00:16  0:00:16 --:--:--  812k
+ dirname sh
+ cd .
+ [ 1 -lt 1 ]
+ INSTALL_DIRECTORY=/usr/local/bin
+ mkdir -p /usr/local/bin
+ [ -t 0 ]
+ curl --location --output /usr/local/bin/extract-xiso https://github.com/timonier/extract-xiso/raw/master/bin/cmd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   136  100   136    0     0      8      0  0:00:17  0:00:15  0:00:02    39
100  1054  100  1054    0     0     64      0  0:00:16  0:00:16 --:--:--    64
+ chmod +x /usr/local/bin/extract-xiso
>

<ka@ka-HP-EliteBook-2570p ~ $ docker run -it
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
ka@ka-HP-EliteBook-2570p ~ $ extract-xiso -h
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
ka@ka-HP-EliteBook-2570p ~ $ docker run extract-xiso -h
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.>

<ka@ka-HP-EliteBook-2570p ~ $ sudo docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

ka@ka-HP-EliteBook-2570p ~ $ sudo docker run extract-xiso -v
Unable to find image 'extract-xiso:latest' locally
docker: Error response from daemon: pull access denied for extract-xiso, repository does not exist or may require 'docker login'.
See 'docker run --help'.
ka@ka-HP-EliteBook-2570p ~ $ 
>

Sorry to bothering you, I know you have better things to do.

**Comment by Tea-pot** [comment]
Hello @mauchede 
I dig a little bit regarding to this issue and what I have found is:
https://github.com/docker/docker-snap/issues/1

long story short extract-xiso is working fine, there is an issue with docker 
Using docker requires sudo #1
I did the same which is written there in the comments section, extract-xiso is working fine:
I did as @Hugo-Gomez advised 
`sudo gpasswd -a $USER docker `
Magic happened and:
`ka@ka-HP-EliteBook-2570p ~/Downloads $ sudo extract-xiso -h
extract-xiso v2.7.1 (01.11.14) for linux - written by in <in@fishtank.com>

  Usage:

    extract-xiso [options] [-[lrx]] <file1.xiso> [file2.xiso] ...
    extract-xiso [options] -c <dir> [name] [-c <dir> [name]] ...

  Mutually exclusive modes:

    -c <dir> [name]     Create xiso from file(s) starting in (local or remote)
                          <dir>.  If the [name] parameter is specified, the
                          xiso will be created with the (path and) name given,
                          otherwise the xiso will be created in the current
                          directory with the name <dir>.iso.  The -c option
                          may be specified multiple times to create multiple
                          xiso images.
    -l                  List files in xiso(s).
    -r                  Rewrite xiso(s) as optimized xiso(s).
    -x                  Extract xiso(s) (the default mode if none is given).
                          If no directory is specified with -d, a directory
                          with the name of the xiso (minus the .iso portion)
                          will be created in the current directory and the
                          xiso will be expanded there.

  Options:

    -d <directory>      In extract mode, expand xiso in <directory>.
                        In rewrite mode, rewrite xiso in <directory>.
                        This option is required when extracting to an ftp
                          server.
    -D                  In rewrite mode, delete old xiso after processing.
    -h                  Print this help text and exit.
    -f <ftp_server>     In create or extract mode, use <ftp_server> instead of
                          the local filesystem.
    -m                  In create or rewrite mode, disable automatic .xbe
                          media enable patching (not recommended).
    -p <password>       Ftp password (defaults to "xbox")
    -q                  Run quiet (suppress all non-error output).
    -Q                  Run silent (suppress all output).
    -s                  Skip $SystemUpdate folder.
    -u <user name>      Ftp user name (defaults to "xbox")
    -v                  Print version information and exit.
`
Unfortunately no luck with Windows, but it does not matter, at lease to me.

cheers, thank you for your time, now I need to just figure out how to use it.
Best regards.

**Comment by Tea-pot** [comment]
Hello @mauchede
Thank you for your reply.
I have learned much while I was trying to figure it out. 
Thank you for advice, I found docker interesting while I was reading. 
Thank you for your patience and your time.
Also `extract-xiso` is great and powerful tool, thank you for maintaining it.
Cheers,
Best regards!
