### ISSUE TITLE
2.7.1 Build Issue

### ISSUE THREAD

**Issue by mnadareski** [timonier/extract-xiso#3]
Using the source distribution of 2.7.1 (last one I could find without requiring Docker), I ran into the following build issue using MSYS2:

```
Ftpfopen.c:30:8: error: unknown type name 'pthread_mutex_t'
 static pthread_mutex_t  s_fds_mutex;
        ^~~~~~~~~~~~~~~
```

**Comment by mauchede** [comment]
Hello @mnadareski,

Sorry for the late response. I am not the creator of `extract-xiso` (I just create a Docker image with `extract-xiso` inside). You should report this issue on the [official "extract-xiso" repository](https://sourceforge.net/projects/extract-xiso/).
